### ISSUE TITLE
Input file format for sfsR

### ISSUE THREAD

**Issue by Tman3** [andrewparkermorgan/sfsr#1]
I google this Rscript for ananlyzing site frequency spectrum in R.

Would like to find out more how to use it in R. Do you have some examples?  The data set I have is from vcftools.  The file format is as follows for 14 chromosomes:

`CHROM	POS	N_ALLELES	N_CHR	{ALLELE:FREQ}
A	13	2	22	T:0.909091	C:0.0909091
A	14	2	22	G:0.636364	A:0.363636`

Is the above file format ready for input into sfsR?

**Comment by andrewparkermorgan** [comment]
No.

The `sfsR` package has some tools for analyzing site frequency spectra, but not for calculating them in the first place from sequencing data. The package further requires that the SFS be "polarized" (or "unfolded"), ie. requires that the ancestral allele is known.

The SFS is like a histogram of the frequency of the derived allele across multiple sites. For a sample of $m$ individuals (assuming a diploid organism like human or mouse), the SFS is a vector of size $2m+1$ in which the $i$th entry is the number of sites at which $i$ chromosomes have the derived allele.

If you knew which allele was the derived one, you could probably use your file to compute the SFS. There are also tools to compute the SFS from aligned sequencing reads, like `ANGSD`  (http://www.popgen.dk/angsd/index.php/ANGSD).
